kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ template "webapp.fullname" . }}
  labels:
    app: {{ template "webapp.name" . }}
    chart: {{ template "webapp.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
        <head>
            <meta charset="UTF-8">
            <title>Hello!</title>
        </head>
        <body>
            <h1>Test Page</h1>
            <p>Hello World!</p>
        </body>
    </html>